name: CI Mysql
on:
  pull_request:
    branches:
      - master
jobs:
  minitest:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    services:
      mysql:
        image: mysql/mysql-server:5.7
        ports:
          - "3306:3306"
        env:
          MYSQL_USER: with_advisory
          MYSQL_PASSWORD: with_advisory_pass
          MYSQL_DATABASE: with_advisory_lock_test
          MYSQL_ROOT_HOST: '%'
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
          - '3.3'
          - 'truffleruby'
        rails:
          - 7.1
          - 7.0
          - 6.1
        adapter:
          - mysql2://with_advisory:with_advisory_lock_test@0/with_advisory_lock_test
          - trilogy://with_advisory:with_advisory_lock_test@0/with_advisory_lock_test
        include:
          - ruby: jruby
            rails: activerecord_6.1
            adapter: jdbcmysql://with_advisory:with_advisory_pass@0/with_advisory_lock_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: latest
        env:
          BUNDLE_GEMFILE:  gemfiles/activerecord_${{ matrix.rails }}.gemfile
      - name: Test
        env:
          BUNDLE_GEMFILE: gemfiles/activerecord_${{ matrix.rails }}.gemfile
          DATABASE_URL: ${{ matrix.adapter }}
          WITH_ADVISORY_LOCK_PREFIX: ${{ github.run_id }}
        run: bundle exec rake
