name: CI Mysql 8.0
on:
  pull_request:
    branches:
      - master

concurrency:
  group: ci-mysql8-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  minitest:
    runs-on: ubuntu-latest
    name: CI Mysql 8.0 Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }} / Adapter ${{ matrix.adapter }}
    services:
      mysql:
        image: mysql/mysql-server
        ports:
          - 3306
        env:
          MYSQL_USER: with_advisory
          MYSQL_PASSWORD: with_advisory_pass
          MYSQL_DATABASE: with_advisory_lock_test
          MYSQL_ROOT_HOST: '%'
    strategy:
      fail-fast: false
      matrix:
        ruby:
#          - '3.2'
#          - '3.1'
#          - '3.0'
#          - '2.7'
          - '3.3'
          - 'truffleruby'
        rails:
          - 7.1
          - "7.0"
          - 6.1
        adapter:
          - mysql2
#          - trilogy://with_advisory:with_advisory_pass@0/with_advisory_lock_test  Trilogy is not supported by mysql 8 with new encryption
        include:
          - ruby: jruby
            rails: 6.1
            adapter: jdbcmysql
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: latest
        env:
          BUNDLE_GEMFILE:  gemfiles/activerecord_${{ matrix.rails }}.gemfile
      - name: Test
        env:
          BUNDLE_GEMFILE: gemfiles/activerecord_${{ matrix.rails }}.gemfile
          DATABASE_URL: ${{ matrix.adapter }}://with_advisory:with_advisory_pass@0:${{ job.services.mysql.ports[3306] }}/with_advisory_lock_test
          WITH_ADVISORY_LOCK_PREFIX: ${{ github.run_id }}
        run: bundle exec rake
