name: CI Postgresql
on:
  pull_request:
    branches:
      - master
concurrency:
    group: ci-postgresql-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
  minitest:
    runs-on: ubuntu-latest
    name: CI Postgresql Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }} / Adapter ${{ matrix.adapter }}
    services:
      postgres:
        image: 'postgres:16-alpine'
        ports:
         - '5432'
        env:
          POSTGRES_USER: with_advisory
          POSTGRES_PASSWORD: with_advisory_pass
          POSTGRES_DB: with_advisory_lock_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.4'
          - 'truffleruby'
        rails:
          - 7.1
          - 7.2
          - "8.0"
        adapter:
          - postgres
        include:
          - ruby: jruby
            rails: 7.1
            adapter: jdbcpostgresql
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: latest
        env:
          BUNDLE_GEMFILE:  gemfiles/activerecord_${{ matrix.rails }}.gemfile
      - name: Test
        env:
          BUNDLE_GEMFILE:  gemfiles/activerecord_${{ matrix.rails }}.gemfile
          DATABASE_URL: ${{ matrix.adapter }}://with_advisory:with_advisory_pass@localhost:${{ job.services.postgres.ports[5432] }}/with_advisory_lock_test
          WITH_ADVISORY_LOCK_PREFIX: ${{ github.run_id }}
        run: bundle exec rake
