name: CI Sqlite3

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ci-sqlite3-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  minitest:
    runs-on: ubuntu-latest
    name: CI Sqlite3 Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }} / Adapter ${{ matrix.adapter }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
#          - '3.2'
#          - '3.1'
#          - '3.0'
#          - '2.7'
          - '3.3'
          - 'truffleruby'
        rails:
          - 7.1
          - "7.0"
          - 6.1
        adapter:
          - sqlite3
        include:
          - ruby: jruby
            rails: 6.1
            adapter: jdbcsqlite3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: latest
        env:
          BUNDLE_GEMFILE: gemfiles/activerecord_${{ matrix.rails }}.gemfile

      - name: Test
        env:
          BUNDLE_GEMFILE: gemfiles/activerecord_${{ matrix.rails }}.gemfile
          DATABASE_URL: ${{ matrix.adapter }}:///tmp/test.sqlite3
          WITH_ADVISORY_LOCK_PREFIX: ${{ github.run_id }}
        run: bundle exec rake
